# Problem: Find the Difference
# LeetCode URL: https://leetcode.com/problems/find-the-difference/description/
# Description: You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        lst_s=list(s)
        lst_t=list(t)
        for ch in lst_s:
            if ch in lst_t:
                lst_t.remove(ch)
        
        if len(lst_t) > 0:
            return lst_t[0]
        else:
            return ""
        